NEW_MODULE_IN_MODULE = 'NEW_MODULE_IN_MODULE'
NEW_CLASS_IN_MODULE = 'NEW_CLASS_IN_MODULE'
NEW_METHOD_IN_MODULE = 'NEW_METHOD_IN_MODULE'
NEW_VARIABLE_IN_MODULE = 'NEW_VARIABLE_IN_MODULE'
MISSING_MODULE_IN_MODULE = 'MISSING_MODULE_IN_MODULE'
MISSING_CLASS_IN_MODULE = 'MISSING_CLASS_IN_MODULE'
MISSING_METHOD_IN_MODULE = 'MISSING_METHOD_IN_MODULE'
MISSING_VARIABLE_IN_MODULE = 'MISSING_VARIABLE_IN_MODULE'
CHANGED_TYPE_IN_MODULE = 'CHANGED_TYPE_IN_MODULE'
NEW_CLASS_IN_CLASS = 'NEW_CLASS_IN_CLASS'
NEW_METHOD_IN_CLASS = 'NEW_METHOD_IN_CLASS'
NEW_PROPERTY_IN_CLASS = 'NEW_PROPERTY_IN_CLASS'
NEW_STATIC_METHOD_IN_CLASS = 'NEW_STATIC_METHOD_IN_CLASS'
NEW_CLASS_METHOD_IN_CLASS = 'NEW_CLASS_METHOD_IN_CLASS'
NEW_VARIABLE_IN_CLASS = 'NEW_VARIABLE_IN_CLASS'
MISSING_CLASS_IN_CLASS = 'MISSING_CLASS_IN_CLASS'
MISSING_METHOD_IN_CLASS = 'MISSING_METHOD_IN_CLASS'
MISSING_PROPERTY_IN_CLASS = 'MISSING_PROPERTY_IN_CLASS'
MISSING_STATIC_METHOD_IN_CLASS = 'MISSING_STATIC_METHOD_IN_CLASS'
MISSING_CLASS_METHOD_IN_CLASS = 'MISSING_CLASS_METHOD_IN_CLASS'
MISSING_VARIABLE_IN_CLASS = 'MISSING_VARIABLE_IN_CLASS'
CHANGED_TYPE_IN_CLASS = 'CHANGED_TYPE_IN_CLASS'
ADDED_VARGS_IN_METHOD = 'ADDED_VARGS_IN_METHOD'
ADDED_KWARGS_IN_METHOD = 'ADDED_KWARGS_IN_METHOD'
ADDED_DEFAULT_IN_METHOD = 'ADDED_DEFAULT_IN_METHOD'
ADDED_ARG_WITH_DEFAULT_IN_METHOD = 'ADDED_ARG_WITH_DEFAULT_IN_METHOD'
ADDED_ARG_WTHOUT_DEFAULT_IN_METHOD = 'ADDED_ARG_WTHOUT_DEFAULT_IN_METHOD'
REMOVED_VARGS_IN_METHOD = 'REMOVED_VARGS_IN_METHOD'
REMOVED_KWARGS_IN_METHOD = 'REMOVED_KWARGS_IN_METHOD'
REMOVED_DEFAULT_IN_METHOD = 'REMOVED_DEFAULT_IN_METHOD'
REMOVED_ARG_IN_METHOD = 'REMOVED_ARG_IN_METHOD'
CHANGED_ARGS_IN_METHOD = 'CHANGED_ARGS_IN_METHOD'
CHANGED_ARG_ORDER_IN_METHOD = 'CHANGED_ARG_ORDER_IN_METHOD'
CHANGED_DEFAULT_IN_METHOD = 'CHANGED_DEFAULT_IN_METHOD'
ADDED_BASE_CLASS = "ADDED_BASE_CLASS"
REMOVED_BASE_CLASS = "REMOVED_BASE_CLASS"

CHANGES = [
    NEW_MODULE_IN_MODULE,
    NEW_CLASS_IN_MODULE,
    NEW_METHOD_IN_MODULE,
    NEW_VARIABLE_IN_MODULE,
    MISSING_MODULE_IN_MODULE,
    MISSING_METHOD_IN_MODULE,
    NEW_METHOD_IN_CLASS,
    MISSING_VARIABLE_IN_MODULE,
    CHANGED_TYPE_IN_MODULE,
    NEW_CLASS_IN_CLASS,
    NEW_METHOD_IN_CLASS,
    NEW_PROPERTY_IN_CLASS,
    NEW_STATIC_METHOD_IN_CLASS,
    NEW_CLASS_METHOD_IN_CLASS,
    NEW_VARIABLE_IN_CLASS,
    MISSING_CLASS_IN_CLASS,
    MISSING_METHOD_IN_CLASS,
    MISSING_PROPERTY_IN_CLASS,
    MISSING_STATIC_METHOD_IN_CLASS,
    MISSING_CLASS_METHOD_IN_CLASS,
    MISSING_VARIABLE_IN_CLASS,
    CHANGED_TYPE_IN_CLASS,
    ADDED_VARGS_IN_METHOD,
    ADDED_KWARGS_IN_METHOD,
    ADDED_DEFAULT_IN_METHOD,
    ADDED_ARG_WITH_DEFAULT_IN_METHOD,
    ADDED_ARG_WTHOUT_DEFAULT_IN_METHOD,
    REMOVED_VARGS_IN_METHOD,
    REMOVED_DEFAULT_IN_METHOD,
    REMOVED_ARG_IN_METHOD,
    CHANGED_ARGS_IN_METHOD,
    CHANGED_ARG_ORDER_IN_METHOD,
    CHANGED_DEFAULT_IN_METHOD,
    ADDED_BASE_CLASS,
    REMOVED_BASE_CLASS
]
